sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: z/pBjjXbpS1pD41ElLq13chxTYBESBP5ogqphR40Zsj5YQmGdWMa1BORpagpEcICf3KGVa9srmXahn0+p+qyPjixuTF3pYSZg3niQuaRzJUKrehRIVj1034AbFb5mysishmmiFW67CbTOORqv6f0mjQt+PSU+DRo/Ox4of0IE07mdKtiICvsXRdP9fFS6LEZqC8CPIPSduKTOhZbgZMRqutp7YrpOCILXIk3CojGlBFHPA/abqDk9OcSKaOsAhKR8cxLtbGM/sb/DDGHmKFblCQkD2vp/0gz7Qo9dgCJpJgnS1rikf1ywI35G7Ee6x+7nm1I3swfVC6rIpcEJAWtHOcYlqSqoMjCtXp5KcKVHApKpKpRiPqS03SviSw213UY0PxTOSZByyoP3qT4M1tT80jU4hjzaaSjcq4GIMdgYiyXQcS2NPoQN6gwEMceKupLFTc66YYzRQTq1AWl4emHVrFBxcswaG2gxhZmNX7UEHsm8jZG96lJ4BIbIWkELBszhawfCXA851rZg/yxeQ5NffROyZ60yXOazfzI4Kum76bXwamZgLscSJ68K+vXLh1FGSZVg9r6k0xJHXv7N3LTQd+fo5CFn9T7yvcaM9Jhkflo6HLIE0a0IgXsRQXTIM/RWiar74qrGMumX+qeP+oojSO7y7z3QV2lewqZ/D8+814=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-God-of-His-Fathers--Tales-of-the-Klondyke_1655
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy